export const jobLessons=[
{level:'Job German A1',title:'First day at work',skill:'Greet your manager and say you are ready',model:'Guten Morgen. Ich bin neu hier.',teach:['Use short useful sentences first.','Ich bin neu hier means I am new here.','Ich bin bereit means I am ready.'],words:[['Guten Morgen','good morning'],['neu hier','new here'],['bereit','ready'],['die Arbeit','work']],test:[['Translate: Good morning.','Guten Morgen.','job'],['Translate: I am new here.','Ich bin neu hier.','sein'],['Translate: I am ready.','Ich bin bereit.','sein'],['Translate: work.','die Arbeit','article']]},
{level:'Job German A1',title:'Ask for help',skill:'Never get stuck silently',model:'Können Sie mir bitte helfen?',teach:['This is one of the most important workplace phrases.','If you do not understand, say it early and politely.','Use langsam for slowly and wiederholen for repeat.'],words:[['helfen','to help'],['wiederholen','to repeat'],['langsam','slowly'],['verstehen','to understand']],test:[['Translate: Can you help me please?','Können Sie mir bitte helfen?','job'],['Translate: I do not understand.','Ich verstehe nicht.','job'],['Translate: Please repeat that.','Bitte wiederholen Sie das.','job'],['Translate: Slowly, please.','Langsam, bitte.','job']]},
{level:'Job German A1',title:'Time and breaks',skill:'Understand start time and breaks',model:'Ich fange um acht Uhr an.',teach:['Jobs use time constantly.','um acht Uhr means at eight o’clock.','Pause means break.'],words:[['anfangen','to start'],['aufhören','to stop'],['die Pause','the break'],['um acht Uhr','at 8 o’clock']],test:[['Translate: I start at eight.','Ich fange um acht Uhr an.','job'],['Translate: When do I start?','Wann fange ich an?','question'],['Translate: break.','die Pause','article'],['Translate: I am finished.','Ich bin fertig.','sein']]},
{level:'Job German A1',title:'Simple instructions',skill:'Understand what someone asks you to do',model:'Was soll ich machen?',teach:['A beginner should not stay silent when instructions are unclear.','Was soll ich machen? means What should I do?','Bitte zeigen Sie mir das means Please show me that.'],words:[['machen','to do'],['zeigen','to show'],['hier','here'],['fertig','finished']],test:[['Translate: What should I do?','Was soll ich machen?','job'],['Translate: Please show me that.','Bitte zeigen Sie mir das.','job'],['Translate: I am finished.','Ich bin fertig.','sein'],['Translate: here.','hier','vocab']]},
{level:'Job German A1',title:'Workplace objects',skill:'Ask where useful things are',model:'Wo ist der Besen?',teach:['Learn the whole noun with der, die or das.','Wo ist...? means Where is...?','Ich brauche... means I need...'],words:[['der Besen','the broom'],['der Eimer','the bucket'],['das Tuch','the cloth'],['die Kasse','the till/register']],test:[['Translate: Where is the broom?','Wo ist der Besen?','question'],['Translate: the bucket.','der Eimer','article'],['Translate: I need the cloth.','Ich brauche das Tuch.','job'],['Translate: Where is the till?','Wo ist die Kasse?','question']]},
{level:'Job German A1',title:'Polite customer phrases',skill:'Buy time and stay polite',model:'Einen Moment, bitte.',teach:['Short polite phrases are enough at A1.','Einen Moment, bitte buys time.','Ich hole Hilfe means I will get help.'],words:[['bitte','please'],['danke','thanks'],['einen Moment','one moment'],['Hilfe','help']],test:[['Translate: One moment, please.','Einen Moment, bitte.','job'],['Translate: Thank you.','Danke.','vocab'],['Translate: I will get help.','Ich hole Hilfe.','job'],['Translate: Can I help you?','Kann ich Ihnen helfen?','job']]},
{level:'Job German A1',title:'Saying yes, no, and maybe',skill:'Answer simple workplace questions',model:'Ja, das kann ich machen.',teach:['You need simple answers before long conversations.','Das kann ich machen means I can do that.','Heute nicht means not today.'],words:[['ja','yes'],['nein','no'],['vielleicht','maybe'],['heute nicht','not today']],test:[['Translate: Yes, I can do that.','Ja, das kann ich machen.','job'],['Translate: No, not today.','Nein, heute nicht.','job'],['Translate: maybe.','vielleicht','vocab'],['Translate: I cannot do that.','Ich kann das nicht machen.','job']]},
{level:'Job German A1',title:'Basic small talk at work',skill:'Respond to common friendly phrases',model:'Wie geht es Ihnen?',teach:['Work conversations often start with polite small talk.','Ihnen is the polite you.','Keep your answer short.'],words:[['Wie geht es Ihnen?','How are you?'],['gut','good'],['nicht schlecht','not bad'],['danke','thanks']],test:[['Translate: How are you?','Wie geht es Ihnen?','job'],['Translate: I am good, thanks.','Mir geht es gut, danke.','job'],['Translate: not bad.','nicht schlecht','vocab'],['Translate: Thank you.','Danke.','vocab']]},
{level:'Job German A1',title:'A1 job conversation checkpoint',skill:'Handle a simple first-day conversation',model:'Guten Morgen. Ich bin neu hier. Können Sie mir bitte helfen?',checkpoint:true,teach:['This checkpoint mixes the workplace basics.','The goal is not perfect grammar.','The goal is to survive a simple work conversation.'],words:[['neu hier','new here'],['Ich verstehe nicht','I do not understand'],['Wann fange ich an?','When do I start?'],['Ich bin fertig','I am finished']],test:[['Translate: I am new here.','Ich bin neu hier.','sein'],['Translate: Can you help me please?','Können Sie mir bitte helfen?','job'],['Translate: When do I start?','Wann fange ich an?','question'],['Translate: I do not understand.','Ich verstehe nicht.','job']]}
];
