export const homeLifeLessons=[
{level:'Home Life A1',title:'At home basics',skill:'Talk about your home and room',model:'Ich bin zu Hause.',teach:['Home German helps with daily life.','zu Hause means at home.','Use Ich brauche... for things you need.'],words:[['zu Hause','at home'],['das Zimmer','the room'],['die Küche','the kitchen'],['das Bad','the bathroom']],test:[['Translate: I am at home.','Ich bin zu Hause.','home'],['Translate: the room.','das Zimmer','article'],['Translate: Where is the bathroom?','Wo ist das Bad?','question'],['Translate: I need the kitchen.','Ich brauche die Küche.','home']]},
{level:'Home Life A1',title:'Food and drink at home',skill:'Say what you need or want',model:'Ich möchte Wasser trinken.',teach:['Ich möchte means I would like.','trinken means to drink.','essen means to eat.'],words:[['Wasser','water'],['Kaffee','coffee'],['Brot','bread'],['essen','to eat']],test:[['Translate: I would like water.','Ich möchte Wasser.','home'],['Translate: I drink coffee.','Ich trinke Kaffee.','home'],['Translate: bread.','Brot','vocab'],['Translate: I would like to eat.','Ich möchte essen.','home']]},
{level:'Home Life A1',title:'Family and people',skill:'Talk about family simply',model:'Meine Familie ist in England.',teach:['Meine means my for many family words.','Keep family sentences short at A1.','Use ist for one person and sind for more than one.'],words:[['meine Familie','my family'],['meine Mutter','my mother'],['mein Vater','my father'],['mein Kind','my child']],test:[['Translate: my family.','meine Familie','home'],['Translate: My mother is here.','Meine Mutter ist hier.','home'],['Translate: My father is at home.','Mein Vater ist zu Hause.','home'],['Translate: my child.','mein Kind','home']]},
{level:'Home Life A1',title:'Problems at home',skill:'Explain simple problems',model:'Ich habe ein Problem.',teach:['This is useful for landlords, neighbours, or repairs.','Ich habe ein Problem means I have a problem.','Use kaputt for broken.'],words:[['das Problem','the problem'],['kaputt','broken'],['laut','loud'],['kalt','cold']],test:[['Translate: I have a problem.','Ich habe ein Problem.','home'],['Translate: It is broken.','Es ist kaputt.','home'],['Translate: It is cold.','Es ist kalt.','home'],['Translate: loud.','laut','vocab']]}
];

export const socialLifeLessons=[
{level:'Social Life A1',title:'Meeting people',skill:'Start a simple friendly conversation',model:'Hallo, wie geht es dir?',teach:['dir is informal you.','Use Ihnen for polite situations.','Start simple: hello, name, how are you.'],words:[['Hallo','hello'],['Wie geht es dir?','How are you?'],['gut','good'],['danke','thanks']],test:[['Translate: Hello, how are you?','Hallo, wie geht es dir?','social'],['Translate: I am good, thanks.','Mir geht es gut, danke.','social'],['Translate: thanks.','danke','vocab'],['Translate: good.','gut','vocab']]},
{level:'Social Life A1',title:'Making plans',skill:'Suggest a simple time or place',model:'Hast du heute Zeit?',teach:['Zeit means time.','heute means today.','Use Hast du...? with friends.'],words:[['heute','today'],['morgen','tomorrow'],['Zeit','time'],['treffen','to meet']],test:[['Translate: Do you have time today?','Hast du heute Zeit?','social'],['Translate: tomorrow.','morgen','vocab'],['Translate: We meet tomorrow.','Wir treffen uns morgen.','social'],['Translate: I have time.','Ich habe Zeit.','haben']]},
{level:'Social Life A1',title:'Cafe conversation',skill:'Order and speak politely',model:'Ich möchte einen Kaffee, bitte.',teach:['Use Ich möchte... to order politely.','bitte means please.','danke means thanks.'],words:[['ein Kaffee','a coffee'],['ein Wasser','a water'],['bitte','please'],['bezahlen','to pay']],test:[['Translate: I would like a coffee, please.','Ich möchte einen Kaffee, bitte.','social'],['Translate: I would like water.','Ich möchte Wasser.','social'],['Translate: Can I pay?','Kann ich bezahlen?','social'],['Translate: please.','bitte','vocab']]},
{level:'Social Life A1',title:'When you do not understand',skill:'Keep a conversation going',model:'Entschuldigung, ich verstehe nicht.',teach:['This phrase saves conversations.','Do not panic if you do not understand.','Ask them to repeat slowly.'],words:[['Entschuldigung','excuse me'],['ich verstehe nicht','I do not understand'],['noch einmal','again'],['langsam','slowly']],test:[['Translate: Excuse me, I do not understand.','Entschuldigung, ich verstehe nicht.','social'],['Translate: Again, please.','Noch einmal, bitte.','social'],['Translate: Slowly, please.','Langsam, bitte.','social'],['Translate: I understand.','Ich verstehe.','social']]}
];
